### PR TITLE
[#319] Logo added

### PR DESCRIPTION
**Pull request by ananya224**
Related to issue #319 

**Describe the Pull Request**
Adds a logo

- [ ] I read contribution guidelines
- [ ] Pull request introduces a BC-Break
- [ ] Pull request is covered by tests
- [ ] Pull request is properly documented in docs

### CODE REVIEW

**Review by kpicaza — COMMENTED** [review]
Thanks for sharing your work!!! The logo looks good, pretty much professional than the red "Ph" I'd created. It's possible to have a transparent background? It will make it easier to integrate in the README files, websites favicons, and so on.

Good job!!! I'll wait for other project members to check before approving.

**Comment by ananya224** [comment]
Yeah! adding a transparent one

**Review by pcs289 — APPROVED** [review]
🚀  This logo looks awesome! Thanks for being part of this community :)

**Review by xserrat — APPROVED** [review]
Looks really good @ananya224 !! Thank you so much for your contribution 🙌🏽🙌🏽

**Review by kpicaza — APPROVED** [review]
🎉🎉🎉

**Comment by luismartinmartinez** [comment]
Hey @ananya224 thanks a lot for this nice logo!! We love it!

**Pull request merged**
